export const POST_GET_DATA = 'POST_GET_DATA'

export const POST_GET_DATA_COMPLETED = 'POST_GET_DATA_COMPLETED'

export const LOADING = 'LOADING';

export const LOADING_COMPLETED = 'LOADING_COMPLETED';

export const CALL_MIDDLEWARE = 'CALL_MIDDLEWARE';

export const CALL_MIDDLEWARE_COMPLETED = 'CALL_MIDDLEWARE_COMPLETED';
